# Generated by Django 4.0.4 on 2022-05-16 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_first_visit_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_title', models.CharField(max_length=100)),
                ('membership_description', models.CharField(max_length=100)),
                ('membership_monthly_cost', models.FloatField()),
                ('membership_annual_discount_percentage', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_up_date', models.DateField()),
                ('cancelled_date', models.DateField()),
                ('discretionary_discount', models.IntegerField()),
                ('membershiptype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.membershiptype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_title', models.CharField(max_length=100)),
                ('benefit_details', models.CharField(max_length=250)),
                ('membership_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.membershiptype')),
            ],
        ),
    ]
