# Generated by Django 4.0.4 on 2022-05-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_membershiptype_usermembership_membershipbenefit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermembership',
            name='cancelled_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
