# Generated by Django 4.0.4 on 2022-05-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_usermembership_cancelled_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermembership',
            name='discretionary_discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
