# Generated by Django 4.0.4 on 2022-05-06 15:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_prometheus.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentMeasurementUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=10)),
                ('unit_description', models.CharField(blank=True, max_length=200, null=True)),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin('ComponentMeasurementUnit'), models.Model),
        ),
        migrations.CreateModel(
            name='StorageAreaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=10)),
                ('type_description', models.CharField(blank=True, max_length=200, null=True)),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin('StorageAreaType'), models.Model),
        ),
        migrations.CreateModel(
            name='StorageArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_area_name', models.CharField(max_length=100)),
                ('parent_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stockkeeper.storagearea')),
                ('storage_area_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockkeeper.storageareatype')),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin('StorageArea'), models.Model),
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=100)),
                ('mpn', models.CharField(blank=True, max_length=100, null=True)),
                ('upc', models.IntegerField(blank=True, null=True)),
                ('qty', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('measurement_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockkeeper.componentmeasurementunit')),
                ('storage_area', models.ManyToManyField(to='stockkeeper.storagearea')),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin('Component'), models.Model),
        ),
    ]
