# Generated by Django 4.0.4 on 2022-05-07 06:32

from django.db import migrations, models
import django_prometheus.models


class Migration(migrations.Migration):

    dependencies = [
        ('stockkeeper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=250)),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin('ComponentType'), models.Model),
        ),
    ]
