# Generated by Django 4.0.4 on 2022-05-07 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockkeeper', '0002_componenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='component_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stockkeeper.componenttype'),
            preserve_default=False,
        ),
    ]
