# Generated by Django 4.0.4 on 2022-05-17 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockkeeper', '0003_component_component_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='componenttype',
            name='parent_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stockkeeper.componenttype'),
        ),
    ]
