# Generated by Django 4.0.4 on 2022-05-17 14:28

from django.db import migrations, models
import django.db.models.deletion
import django_prometheus.models


class Migration(migrations.Migration):

    dependencies = [
        ('stockkeeper', '0004_componenttype_parent_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('website', models.URLField()),
                ('primary_contact_email', models.EmailField(max_length=254)),
                ('reseller_discount_available', models.BooleanField()),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin('Manufacturer'), models.Model),
        ),
        migrations.AddField(
            model_name='component',
            name='buy_at',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='rrp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='sell_at',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stockkeeper.manufacturer'),
        ),
    ]
