# Generated by Django 4.0.4 on 2022-05-17 14:37

from django.db import migrations, models
import django.db.models.deletion
import django_prometheus.models


class Migration(migrations.Migration):

    dependencies = [
        ('stockkeeper', '0005_manufacturer_component_buy_at_component_rrp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('website', models.URLField()),
                ('primary_contact_email', models.EmailField(max_length=254)),
                ('reseller_discount_available', models.BooleanField()),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin('Vendor'), models.Model),
        ),
        migrations.RemoveField(
            model_name='component',
            name='buy_at',
        ),
        migrations.RemoveField(
            model_name='component',
            name='rrp',
        ),
        migrations.RemoveField(
            model_name='component',
            name='sell_at',
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='buy_direct',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ComponentPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rrp', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('buy_at', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sell_at', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockkeeper.vendor')),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin('Vendor'), models.Model),
        ),
        migrations.AddField(
            model_name='component',
            name='prices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stockkeeper.componentprice'),
        ),
    ]
