# Generated by Django 4.0.4 on 2022-05-17 15:09

from django.db import migrations, models
import django_prometheus.models


class Migration(migrations.Migration):

    dependencies = [
        ('stockkeeper', '0006_vendor_remove_component_buy_at_remove_component_rrp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=3)),
                ('symbol', models.CharField(max_length=2)),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin('Currency'), models.Model),
        ),
    ]
