# Generated by Django 4.0.4 on 2022-05-17 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockkeeper', '0007_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentprice',
            name='buy_currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='buy_currency', to='stockkeeper.currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='componentprice',
            name='sell_currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sell_currency', to='stockkeeper.currency'),
            preserve_default=False,
        ),
    ]
