# Generated by Django 4.0.4 on 2022-05-17 16:48

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stockkeeper', '0009_alter_currency_options_componenttype_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componenttype',
            name='parent_type',
        ),
        migrations.AddField(
            model_name='componenttype',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='stockkeeper.componenttype'),
        ),
    ]
