# Generated by Django 4.0.4 on 2022-05-17 16:58

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stockkeeper', '0010_remove_componenttype_parent_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storagearea',
            name='parent_area',
        ),
        migrations.AddField(
            model_name='storagearea',
            name='level',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storagearea',
            name='lft',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storagearea',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='stockkeeper.storagearea'),
        ),
        migrations.AddField(
            model_name='storagearea',
            name='rght',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storagearea',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
    ]
