# Generated by Django 4.0.4 on 2022-05-17 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockkeeper', '0011_remove_storagearea_parent_area_storagearea_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storagearea',
            old_name='storage_area_name',
            new_name='name',
        ),
    ]
