# Generated by Django 4.0.4 on 2022-05-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockkeeper', '0012_rename_storage_area_name_storagearea_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='componenttype',
            name='shortcode',
            field=models.CharField(default='SBC', max_length=3),
            preserve_default=False,
        ),
    ]
