# Generated by Django 4.0.4 on 2022-05-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockkeeper', '0013_componenttype_shortcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='sku',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
