# Shamelessly stolen from https://blog.healthchecks.io/2020/11/using-github-actions-to-run-django-tests/
name: Django Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 4
      matrix:
        db: [sqlite, postgres, mysql]
        python-version: [3.9]
        include:
          - db: postgres
            db_port: 5432
          - db: mysql
            db_port: 3306

    services:
      postgres:
        image: postgres:10
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: hunter2
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: hunter2
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        poetry install
        pip install braintree mysqlclient apprise
    - name: Run Tests
      env:
        SPACERUNNER_DB_USER: ${{ matrix.db_user }}
        SPACERUNNER_DB_NAME: ${{ matrix.db }}
        SPACERUNNER_DB_HOST: 127.0.0.1
        SPACERUNNER_DB_PORT: ${{ matrix.db_port }}
        SPACERUNNER_DB_PASSWORD: hunter2
        SPACERUNNER_SECRET_KEY: ${{ secrets.SPACERUNNER_SECRET_KEY }}
        SPACERUNNER_OCTOPART_API_KEY: ${{ secrets.SPACERUNNER_OCTOPART_API_KEY }}
      run: |
        python manage.py test -v 2
